// Manages alerts from all providers + auto-generated health alerts

class AlertService {
  constructor() {
    this.alerts = new Map(); // id -> alert
    this.rules = [
      { id: 'cpu-high',          metric: 'cpu',         threshold: 85, severity: 'warning',  message: 'CPU usage above 85%' },
      { id: 'cpu-critical',      metric: 'cpu',         threshold: 95, severity: 'critical', message: 'CPU usage above 95%' },
      { id: 'mem-high',          metric: 'memUsage',    threshold: 85, severity: 'warning',  message: 'Memory usage above 85%' },
      { id: 'disk-high',         metric: 'diskUsage',   threshold: 90, severity: 'warning',  message: 'Disk usage above 90%' },
      { id: 'health-critical',   metric: 'health',      value: 'critical', severity: 'critical', message: 'Resource health is critical' },
      { id: 'connections-high',  metric: 'connections', threshold: 90, severity: 'warning',  message: 'DB connections near limit' },
    ];
  }

  generateFromResources(resources) {
    const generated = [];
    for (const r of resources) {
      for (const rule of this.rules) {
        if (rule.metric === 'health' && r.health === rule.value) {
          const alertId = `health-${r.id}`;
          if (!this.alerts.has(alertId)) {
            const alert = {
              id: alertId,
              title: `${r.name} is ${r.health}`,
              message: `${r.type} in ${r.region} has health status: ${r.health}`,
              severity: rule.severity,
              provider: r.provider,
              service: r.name,
              region: r.region,
              resourceId: r.id,
              time: new Date().toISOString(),
              acknowledged: false,
              autoGenerated: true,
            };
            this.alerts.set(alertId, alert);
            generated.push(alert);
          }
        } else if (rule.metric !== 'health' && r[rule.metric] !== undefined && r[rule.metric] >= rule.threshold) {
          const alertId = `${rule.id}-${r.id}`;
          if (!this.alerts.has(alertId)) {
            const alert = {
              id: alertId,
              title: `${r.name}: ${rule.message}`,
              message: `${r.type} in ${r.region}: ${rule.metric} is ${r[rule.metric]}% (threshold: ${rule.threshold}%)`,
              severity: rule.severity,
              provider: r.provider,
              service: r.name,
              region: r.region,
              resourceId: r.id,
              time: new Date().toISOString(),
              acknowledged: false,
              autoGenerated: true,
            };
            this.alerts.set(alertId, alert);
            generated.push(alert);
          }
        }
      }
    }
    return generated;
  }

  addProviderAlerts(alerts) {
    for (const a of alerts) {
      if (!this.alerts.has(a.id)) {
        this.alerts.set(a.id, a);
      }
    }
  }

  acknowledge(alertId) {
    const alert = this.alerts.get(alertId);
    if (alert) {
      alert.acknowledged = true;
      return true;
    }
    return false;
  }

  getAll() {
    return Array.from(this.alerts.values()).sort((a, b) => {
      const sev = { critical: 0, warning: 1, info: 2 };
      const sevDiff = (sev[a.severity] || 2) - (sev[b.severity] || 2);
      if (sevDiff !== 0) return sevDiff;
      return new Date(b.time) - new Date(a.time);
    });
  }

  clear() {
    this.alerts.clear();
  }

  getStats() {
    const all = this.getAll();
    return {
      total: all.length,
      critical: all.filter(a => a.severity === 'critical' && !a.acknowledged).length,
      warning:  all.filter(a => a.severity === 'warning'  && !a.acknowledged).length,
      unacknowledged: all.filter(a => !a.acknowledged).length,
    };
  }
}

export default AlertService;
